'''
A basic class for handling the log files generated by larpix-scripts
Typical usage:
``
sl = ScriptLogger()
log = ScriptLogger.get_script_log()
log.info(<message>) # print something to script log + stdout
sl.flush_datalog() # store current serial data to file
``
The script log can be accessed from any module via
``
from helpers.logging import ScriptLogger
log = ScriptLogger.get_script_log()
``
'''

import logging
import time
import sys
import os
import larpix
import helpers.pathnames as pathnames

class MakeFileHandler(logging.FileHandler):
    def __init__(self, filename, mode='a', encoding=None, delay=0):            
        pathnames.mkdir_p(os.path.dirname(filename))
        logging.FileHandler.__init__(self, filename, mode, encoding, delay)

class ScriptLogger(class):
    script_logging_format = '%(asctime)s %(levelname)s: %(message)s')
    script_log_level = logging.DEBUG

    def __init__(self, script_logfile=None, data_logfile=None):
        self.start_time = time.time()
        if script_logfile is None:
            self.script_logdir = pathnames.default_script_logdir(self.start_time)
            self.script_logfile = pathnames.default_script_logfile(self.start_time)
        else:
            self.script_logdir = os.path.split(script_logfile)[0]
            self.script_logfile = script_logfile
        if data_logfile is None:
            self.data_logdir = pathnames.default_data_logdir(self.start_time)
            self.data_logfile = pathnames.default_data_logfile(self.start_time)
        else:
            self.data_logdir = os.path.split(data_logfile)[0]
            self.data_logfile = data_logfile

        self.init_script_logging()
        self.script_log.setLevel(self.script_log_level)
        self.script_log.info('initialized script logger')
        self.script_log.info('logging to %s' % self.script_logfile)

        self.init_data_logging()
        self.script_log.info('initialized data logger')
        self.script_log.info('storing data to %s' % self.data_logfile)

    def init_script_logging(self):
        self.script_log = self.get_script_log()
        self.script_log_fhandler = logging.FileHandler(self.script_logfile)
        self.script_log_shandler = logging.StreamHandler(sys.stdout)
        self.script_log_formatter = \
            logging.Formatter(self.script_logging_format)
        self.log.addHandler(self.script_log_fhandler)
        self.log.addHandler(self.script_log_shandler)

    def init_data_logging():
        self.enable_datalog(self.data_logfile)

    @classmethod
    def get_script_log():
        return logging.getLogger(pathnames.script_name)

    def enable_datalog(filename=None):
        if not filename is None:
            self.data_logdir = os.path.split(filename)[0]
            self.data_logfile = filename
        return larpix.enable_logger(self.data_logfile)

    def flush_datalog():
        return larpix.flush_logger()

    def disable_datalog():
        return larpix.disable_logger()
